/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { JudicialChainOfCustody } from './JudicialChainOfCustody.js';
export * as factories from './factories/index.js';
export { JudicialChainOfCustody__factory } from './factories/JudicialChainOfCustody__factory.js';