/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface JudicialChainOfCustodyInterface extends Interface {
    getFunction(nameOrSignature: "anchorHash" | "authorizeAnchor" | "authorizedAnchors" | "getRecord" | "owner" | "revokeAnchor" | "transferOwnership" | "verifyHash"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AnchorAuthorized" | "AnchorRevoked" | "HashAnchored" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'anchorHash', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'authorizeAnchor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'authorizedAnchors', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getRecord', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'revokeAnchor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'verifyHash', values: [BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'anchorHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizeAnchor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizedAnchors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeAnchor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyHash', data: BytesLike): Result;
  }

  
    export namespace AnchorAuthorizedEvent {
      export type InputTuple = [anchor: AddressLike];
      export type OutputTuple = [anchor: string];
      export interface OutputObject {anchor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AnchorRevokedEvent {
      export type InputTuple = [anchor: AddressLike];
      export type OutputTuple = [anchor: string];
      export interface OutputObject {anchor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace HashAnchoredEvent {
      export type InputTuple = [caseId: BytesLike, documentHash: BytesLike, anchoredBy: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [caseId: string, documentHash: string, anchoredBy: string, timestamp: bigint];
      export interface OutputObject {caseId: string, documentHash: string, anchoredBy: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [oldOwner: string, newOwner: string];
      export interface OutputObject {oldOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface JudicialChainOfCustody extends BaseContract {
    
    connect(runner?: ContractRunner | null): JudicialChainOfCustody;
    waitForDeployment(): Promise<this>;

    interface: JudicialChainOfCustodyInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    anchorHash: TypedContractMethod<
      [caseId: BytesLike, documentHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    authorizeAnchor: TypedContractMethod<
      [anchor: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    authorizedAnchors: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    getRecord: TypedContractMethod<
      [caseId: BytesLike, ],
      [[string, bigint, string, boolean] & {documentHash: string, timestamp: bigint, anchoredBy: string, exists: boolean }],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    revokeAnchor: TypedContractMethod<
      [anchor: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    verifyHash: TypedContractMethod<
      [caseId: BytesLike, documentHash: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'anchorHash'): TypedContractMethod<
      [caseId: BytesLike, documentHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'authorizeAnchor'): TypedContractMethod<
      [anchor: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'authorizedAnchors'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getRecord'): TypedContractMethod<
      [caseId: BytesLike, ],
      [[string, bigint, string, boolean] & {documentHash: string, timestamp: bigint, anchoredBy: string, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'revokeAnchor'): TypedContractMethod<
      [anchor: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyHash'): TypedContractMethod<
      [caseId: BytesLike, documentHash: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'AnchorAuthorized'): TypedContractEvent<AnchorAuthorizedEvent.InputTuple, AnchorAuthorizedEvent.OutputTuple, AnchorAuthorizedEvent.OutputObject>;
getEvent(key: 'AnchorRevoked'): TypedContractEvent<AnchorRevokedEvent.InputTuple, AnchorRevokedEvent.OutputTuple, AnchorRevokedEvent.OutputObject>;
getEvent(key: 'HashAnchored'): TypedContractEvent<HashAnchoredEvent.InputTuple, HashAnchoredEvent.OutputTuple, HashAnchoredEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'AnchorAuthorized(address)': TypedContractEvent<AnchorAuthorizedEvent.InputTuple, AnchorAuthorizedEvent.OutputTuple, AnchorAuthorizedEvent.OutputObject>;
      AnchorAuthorized: TypedContractEvent<AnchorAuthorizedEvent.InputTuple, AnchorAuthorizedEvent.OutputTuple, AnchorAuthorizedEvent.OutputObject>;
    

      'AnchorRevoked(address)': TypedContractEvent<AnchorRevokedEvent.InputTuple, AnchorRevokedEvent.OutputTuple, AnchorRevokedEvent.OutputObject>;
      AnchorRevoked: TypedContractEvent<AnchorRevokedEvent.InputTuple, AnchorRevokedEvent.OutputTuple, AnchorRevokedEvent.OutputObject>;
    

      'HashAnchored(bytes32,bytes32,address,uint256)': TypedContractEvent<HashAnchoredEvent.InputTuple, HashAnchoredEvent.OutputTuple, HashAnchoredEvent.OutputObject>;
      HashAnchored: TypedContractEvent<HashAnchoredEvent.InputTuple, HashAnchoredEvent.OutputTuple, HashAnchoredEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }